@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":McSchedulerParser" as McSchedulerParser LOGIC_COLOR
participant ":WorkerAddCommandParser" as WorkerAddCommandParser LOGIC_COLOR
participant "a:WorkerAddCommand" as WorkerAddCommand LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("worker-add\n... u/Mon")
activate LogicManager

LogicManager -> McSchedulerParser : parseCommand("worker-add\n... u/Mon")
activate McSchedulerParser

create WorkerAddCommandParser
McSchedulerParser -> WorkerAddCommandParser
activate WorkerAddCommandParser

WorkerAddCommandParser --> McSchedulerParser
deactivate WorkerAddCommandParser

McSchedulerParser -> WorkerAddCommandParser : parse("... u/Mon")
activate WorkerAddCommandParser

WorkerAddCommandParser -> ParserUtil : parseUnavailabilities("Mon")
activate ParserUtil

ParserUtil -> ParserUtil : createMorningUnavailability\nString("Mon")
ParserUtil -> ParserUtil : createAfternoonUnavailability\nString("Mon")
return
deactivate ParserUtil

create WorkerAddCommand
WorkerAddCommandParser -> WorkerAddCommand
activate WorkerAddCommand

WorkerAddCommand --> WorkerAddCommandParser
deactivate WorkerAddCommand

WorkerAddCommandParser --> McSchedulerParser : a
deactivate WorkerAddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
WorkerAddCommandParser -[hidden]-> McSchedulerParser
destroy WorkerAddCommandParser

McSchedulerParser --> LogicManager : a
deactivate McSchedulerParser

LogicManager -> WorkerAddCommand : execute()
activate WorkerAddCommand

WorkerAddCommand -> Model : addWorker(worker)
activate Model

Model --> WorkerAddCommand
deactivate Model

create CommandResult
WorkerAddCommand -> CommandResult
activate CommandResult

CommandResult --> WorkerAddCommand
deactivate CommandResult

WorkerAddCommand --> LogicManager : result
deactivate WorkerAddCommand

[<--LogicManager
deactivate LogicManager
@enduml
