@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":McSchedulerParser" as McSchedulerParser LOGIC_COLOR
participant ":AssignCommandParser" as AssignCommandParser LOGIC_COLOR
participant "a:AssignCommand" as AssignCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Assignment" as Assignment MODEL_COLOR
end box

[-> LogicManager : execute("assign s/1\nw/1 Cashier")
activate LogicManager

LogicManager -> McSchedulerParser : parseCommand("assign\ns/1 w/1 Cashier")
activate McSchedulerParser

create AssignCommandParser
McSchedulerParser -> AssignCommandParser
activate AssignCommandParser

AssignCommandParser --> McSchedulerParser
deactivate AssignCommandParser

McSchedulerParser -> AssignCommandParser : parse("s/1 w/1 Cashier")
activate AssignCommandParser

create AssignCommand
AssignCommandParser -> AssignCommand
activate AssignCommand

AssignCommand --> AssignCommandParser : a
deactivate AssignCommand

AssignCommandParser --> McSchedulerParser : a
deactivate AssignCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AssignCommandParser -[hidden]-> McSchedulerParser
destroy AssignCommandParser

McSchedulerParser --> LogicManager : a
deactivate McSchedulerParser

LogicManager -> AssignCommand : execute()
activate AssignCommand

create Assignment
AssignCommand -> Assignment
activate Assignment

Assignment -> AssignCommand : assignment
deactivate Assignment

AssignCommand -> Model : addAssignment(assignment)
activate Model

Model --> AssignCommand
deactivate Model

create CommandResult
AssignCommand -> CommandResult
activate CommandResult

CommandResult --> AssignCommand
deactivate CommandResult

AssignCommand --> LogicManager : result
deactivate AssignCommand

[<--LogicManager
deactivate LogicManager
@enduml
