@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":McSchedulerParser" as McSchedulerParser LOGIC_COLOR
participant ":WorkerDeleteCommandParser" as WorkerDeleteCommandParser LOGIC_COLOR
participant "d:WorkerDeleteCommand" as WorkerDeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("worker-delete 1")
activate LogicManager

LogicManager -> McSchedulerParser : parseCommand("worker-delete 1")
activate McSchedulerParser

create WorkerDeleteCommandParser
McSchedulerParser -> WorkerDeleteCommandParser
activate WorkerDeleteCommandParser

WorkerDeleteCommandParser --> McSchedulerParser
deactivate WorkerDeleteCommandParser

McSchedulerParser -> WorkerDeleteCommandParser : parse("1")
activate WorkerDeleteCommandParser

create WorkerDeleteCommand
WorkerDeleteCommandParser -> WorkerDeleteCommand
activate WorkerDeleteCommand

WorkerDeleteCommand --> WorkerDeleteCommandParser : d
deactivate WorkerDeleteCommand

WorkerDeleteCommandParser --> McSchedulerParser : d
deactivate WorkerDeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
WorkerDeleteCommandParser -[hidden]-> McSchedulerParser
destroy WorkerDeleteCommandParser

McSchedulerParser --> LogicManager : d
deactivate McSchedulerParser

LogicManager -> WorkerDeleteCommand : execute()
activate WorkerDeleteCommand

WorkerDeleteCommand -> Model : deleteWorker(1)
activate Model

Model --> WorkerDeleteCommand
deactivate Model

create CommandResult
WorkerDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> WorkerDeleteCommand
deactivate CommandResult

WorkerDeleteCommand --> LogicManager : result
deactivate WorkerDeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
