@startuml
!include style.puml
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

class Tag {
tagName: String
}

class Role {
tagName: String
{static} createRole(String)
}

class Leave {
{static} ROLE_NAME: String
}

Tag <|- Role
Role <|- Leave
Role ..> Leave
@enduml
