@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TakeLeaveCommand" as TakeLeaveCommand LOGIC_COLOR
participant ":AssignCommand" as AssignCommand LOGIC_COLOR
participant ":ReassignCommand" as ReassignCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(userInput)
activate LogicManager

ref over LogicManager
    Parsing user command.
    Refer to Assignment
    implementation.
end ref

LogicManager -> TakeLeaveCommand : execute()
activate TakeLeaveCommand

create AssignCommand
TakeLeaveCommand -> AssignCommand
activate AssignCommand
AssignCommand --> TakeLeaveCommand
deactivate AssignCommand

TakeLeaveCommand -> AssignCommand : execute()
activate AssignCommand

AssignCommand -> Model : assign leave
activate Model

Model --> AssignCommand
deactivate Model

AssignCommand --> TakeLeaveCommand
deactivate AssignCommand

loop for each reassignment
create ReassignCommand
TakeLeaveCommand -> ReassignCommand
activate ReassignCommand
ReassignCommand --> TakeLeaveCommand
deactivate ReassignCommand

TakeLeaveCommand -> ReassignCommand : execute()
activate ReassignCommand

ReassignCommand -> Model: reassign as leave
activate Model

Model --> ReassignCommand
deactivate Model

ReassignCommand --> TakeLeaveCommand
deactivate ReassignCommand
end

TakeLeaveCommand --> LogicManager : commandResult
deactivate TakeLeaveCommand

LogicManager -->[
deactivate LogicManager


@enduml
