@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyMcScheduler <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class McScheduler
Class ReadOnlyMcScheduler
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Worker {
Class Worker
Class Address
Class Email
Class Name
Class Phone
Class UniqueWorkerList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

McScheduler .up.|> ReadOnlyMcScheduler

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" McScheduler
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

McScheduler *--> "1" UniqueWorkerList
UniqueWorkerList o--> "*" Worker
Worker *--> Name
Worker *--> Phone
Worker *--> Email
Worker *--> Address
Worker *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"1" Worker : filtered list
@enduml
