@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyMcScheduler <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class McScheduler
Class ReadOnlyMcScheduler
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Worker {
Class Worker
Class Address
Class Pay
Class Name
Class Phone
Class Unavailability
Class UniqueWorkerList
}

Package Role {
Class Role
Class UniqueRoleList
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

McScheduler .up.|> ReadOnlyMcScheduler

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" McScheduler
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

McScheduler *--> "1" UniqueWorkerList
McScheduler *--> "1" UniqueRoleList
UniqueWorkerList o--> "*" Worker
Worker *--> Name
Worker *--> Phone
Worker *--> Pay
Worker *--> Address
Worker *--> "*" Unavailability
Worker o--> "*" Role
UniqueRoleList o--> "*" Role

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Pay
Pay -[hidden]right-> Unavailability

ModelManager -->"1" Worker : filtered list
@enduml
