@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

McScheduler *-right-> "1" UniqueRoleList

UniqueRoleList o-right-> Role
RoleRequirement *--> "1" Role

@enduml
