@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface McSchedulerStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonMcSchedulerStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> McSchedulerStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonMcSchedulerStorage .left.|> McSchedulerStorage
JsonMcSchedulerStorage .down.> JsonAdaptedWorker
JsonAdaptedWorker .right.> JsonAdaptedRole
@enduml
