@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

McScheduler *-right-> "1" UniqueWorkerList

UniqueWorkerList o-right-> Worker

Worker *--> "1" Name
Worker *--> "1" Phone
Worker *--> "1" Pay
Worker *--> "1" Address
Worker *--> "*" Role
Worker *--> "*" Unavailability
@enduml
